ARG BASE_DIGEST
FROM cyph/base@${BASE_DIGEST}

COPY .local-docker-context /home/gibson/
RUN test -d /home/gibson/.local-docker-context/config && \
	rm -rf /home/gibson/.config 2> /dev/null && \
	mv /home/gibson/.local-docker-context/config /home/gibson/.config ; \
	rm -rf /home/gibson/.local-docker-context

WORKDIR /cyph/commands
CMD /bin/bash
