FROM scratch AS scratch-amd64
ARG BASE_DIGEST_AMD64
ARG BASE_DIGEST=${BASE_DIGEST_AMD64}

FROM scratch AS scratch-arm64
ARG BASE_DIGEST_ARM64
ARG BASE_DIGEST=${BASE_DIGEST_ARM64}

FROM scratch-${TARGETARCH}
ARG BASE_DIGEST
FROM cyph/base@${BASE_DIGEST}

RUN test -d /cyph || sudo mkdir /cyph
RUN sudo chmod 777 /cyph

WORKDIR /cyph
CMD /bin/bash
