application: cyphme
version: master
runtime: go
api_version: go1

inbound_services:
- channel_presence

- url: /analytics/.*
  static_files: analytics.html
  upload: analytics.html
  http_headers:
    Cache-Control: public, max-age=0

- url: /stats[/]?
  login: admin
  script: _go_app
  secure: always

- url: /tasks/.*
  login: admin
  script: _go_app
  secure: always

- url: .*
  script: _go_app
  secure: always
