runtime: go
api_version: go1

handlers:
- url: /analsandbox/.*
  static_files: anal.html
  upload: anal.html
  secure: always
  # default_headers Cache-Control X-Frame-Options Content-Security-Policy X-Content-Security-Policy X-WebKit-CSP

- url: .*
  script: _go_app
  secure: always
