application: cyphme
version: prod
runtime: go
api_version: go1

inbound_services:
- channel_presence

handlers:
- url: .*
  script: _go_app
  secure: always
  http_headers:
    Access-Control-Allow-Methods: POST,GET,OPTIONS,PUT,DELETE
