application: cyphme
version: prod
runtime: go
api_version: go1

inbound_services:
- channel_presence

handlers:
- url: /analytics/.*
  static_files: analytics.html
  upload: analytics.html
  http_headers:
    Cache-Control: public, max-age=0

- url: .*
  script: _go_app
  secure: always
