application: cyphme
version: master
runtime: go
api_version: go1

handlers:
- url: /anal/.*
  static_files: anal.html
  upload: anal.html
  http_headers:
    Cache-Control: public, max-age=0
    Strict-Transport-Security: max-age=31536000; includeSubdomains;

- url: .*
  script: _go_app
  secure: always
