runtime: go116

# Prod-only:
# instance_class: F2

handlers:
- url: /chat-widget.js
  static_files: chat-widget.js
  upload: chat-widget.js
  secure: always
  # default_headers Cache-Control X-Frame-Options Content-Security-Policy

- url: /icon.svg
  static_files: icon.svg
  upload: icon.svg
  secure: always
  # default_headers Cache-Control X-Frame-Options Content-Security-Policy

- url: /test.webm
  static_files: test.webm
  upload: test.webm
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: .*
  script: auto
  secure: always
