version: 2.1

jobs:
  build:
    docker:
      - image: cyph/circleci@sha256:11d2087c63fb3dffbe8d653bb154f3afed666b57fcdae775ae52bc8d8e4c40d3
    resource_class: large
    working_directory: /cyph
    steps:
      - checkout
      - run:
          command: |
            source ~/.bashrc
            /cyph/commands/test.sh --build
          no_output_timeout: 1800

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - prod
                - beta
