version: 2.1

jobs:
  build:
    docker:
      - image: cyph/circleci@sha256:7df5b2251d0afeef8134842bbae8fb9f73f0cc1cf323954b5f9ae376d942119a
    resource_class: xlarge
    working_directory: /cyph
    steps:
      - checkout
      - run:
          command: |
            source ~/.bashrc
            /cyph/commands/test.sh --build
          no_output_timeout: 1800

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - prod
                - beta
