version: 2.1

jobs:
  build:
    docker:
      - image: cyph/circleci@sha256:a6f0e5ba820ff5471467ea2b20ed1ff912fd6e12deb7b079b4b5ba235c3effa5
    resource_class: xlarge
    working_directory: /cyph
    steps:
      - checkout
      - run:
          command: |
            source ~/.bashrc
            /cyph/commands/test.sh --build
          no_output_timeout: 1800

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - prod
                - beta
