version: 2.1

jobs:
  build:
    docker:
      - image: cyph/circleci@sha256:09b61884682af5dd21edb54d10c931d709cb1b52d6df4e9ed32de913a6f0ea1a
    resource_class: xlarge
    working_directory: /cyph
    steps:
      - checkout
      - run:
          command: |
            source ~/.bashrc
            /cyph/commands/test.sh --build
          no_output_timeout: 1800

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - prod
                - beta
