cyphbranch () {
	git describe --tags --exact-match 2> /dev/null || git branch | awk '/^\*/{print $2}'
}

cyphbuild () {
	~/cyph/$(cyphbranch)/docker.sh build --simple
}
cyphdeploy () {
	~/cyph/$(cyphbranch)/docker.sh deploy $*
}
cyphgit () {
	~/cyph/$(cyphbranch)/docker.sh commit $*
}
cyphkill () {
	~/cyph/$(cyphbranch)/docker.sh kill
}
cyphserve () {
	~/cyph/$(cyphbranch)/docker.sh serve
}

cyphcd () {
	cd ~/cyph/master
}

cyphproddeploy () {
	cyphcd
	cd ../prod
	git pull
	git merge origin/master
	git commit -a -m merge
	git push
	cd ../master
	git pull
	git merge origin/prod
	git commit -a -m merge
	git push
	cd ../prod
	git pull
	cyphdeploy --prod
}
