#!/bin/bash

# Firebase Storage reverse proxy setup script for Ubuntu 14.04

conf='dXNlciB3d3ctZGF0YTsKd29ya2VyX3Byb2Nlc3NlcyBhdXRvOwpwaWQgL3J1bi9uZ2lueC5waWQ7CgpldmVudHMgewoJd29ya2VyX2Nvbm5lY3Rpb25zIDEwMjQ7CgltdWx0aV9hY2NlcHQgb2ZmOwp9CgpodHRwIHsKCgkjIwoJIyBCYXNpYyBTZXR0aW5ncwoJIyMKCglzZW5kZmlsZSBvbjsKCXRjcF9ub3B1c2ggb247Cgl0Y3Bfbm9kZWxheSBvbjsKCWtlZXBhbGl2ZV90aW1lb3V0IDY1OwoJdHlwZXNfaGFzaF9tYXhfc2l6ZSAyMDQ4OwoJc2VydmVyX3Rva2VucyBvZmY7CglzZXJ2ZXJfbmFtZXNfaGFzaF9idWNrZXRfc2l6ZSA2NDsKCWluY2x1ZGUgL2V0Yy9uZ2lueC9taW1lLnR5cGVzOwoJZGVmYXVsdF90eXBlIGFwcGxpY2F0aW9uL29jdGV0LXN0cmVhbTsKCgkjIwoJIyBMb2dnaW5nIFNldHRpbmdzCgkjIwoKCWFjY2Vzc19sb2cgb2ZmOwoJZXJyb3JfbG9nIC9kZXYvbnVsbCBjcml0OwoKCSMjCgkjIEd6aXAgU2V0dGluZ3MKCSMjCgoJZ3ppcCBvbjsKCWd6aXBfaHR0cF92ZXJzaW9uIDEuMDsKCWd6aXBfc3RhdGljIGFsd2F5czsKCgkjIwoJIyBTZXJ2ZXIgU2V0dGluZ3MKCSMjCgoJc2VydmVyIHsKCQlsaXN0ZW4gNDQzIHNzbDsKCgkJc3NsX2NlcnRpZmljYXRlIHNzbC9jZXJ0LnBlbTsKCQlzc2xfY2VydGlmaWNhdGVfa2V5IHNzbC9rZXkucGVtOwoJCXNzbF9kaHBhcmFtIHNzbC9kaHBhcmFtcy5wZW07CgoJCXNzbF9zZXNzaW9uX3RpbWVvdXQgMWQ7CgkJc3NsX3Nlc3Npb25fY2FjaGUgc2hhcmVkOlNTTDo1MG07CgoJCXNzbF9wcmVmZXJfc2VydmVyX2NpcGhlcnMgb247CgkJYWRkX2hlYWRlciBTdHJpY3QtVHJhbnNwb3J0LVNlY3VyaXR5ICdtYXgtYWdlPTMxNTM2MDAwOyBpbmNsdWRlU3ViZG9tYWluczsgcHJlbG9hZCc7CgkJc3NsX3Byb3RvY29scyBUTFN2MSBUTFN2MS4xIFRMU3YxLjI7CgkJc3NsX2NpcGhlcnMgJ0VDREhFLVJTQS1BRVMxMjgtR0NNLVNIQTI1NjpFQ0RIRS1FQ0RTQS1BRVMxMjgtR0NNLVNIQTI1NjpFQ0RIRS1SU0EtQUVTMjU2LUdDTS1TSEEzODQ6RUNESEUtRUNEU0EtQUVTMjU2LUdDTS1TSEEzODQ6REhFLVJTQS1BRVMxMjgtR0NNLVNIQTI1NjpESEUtRFNTLUFFUzEyOC1HQ00tU0hBMjU2OmtFREgrQUVTR0NNOkVDREhFLVJTQS1BRVMxMjgtU0hBMjU2OkVDREhFLUVDRFNBLUFFUzEyOC1TSEEyNTY6RUNESEUtUlNBLUFFUzEyOC1TSEE6RUNESEUtRUNEU0EtQUVTMTI4LVNIQTpFQ0RIRS1SU0EtQUVTMjU2LVNIQTM4NDpFQ0RIRS1FQ0RTQS1BRVMyNTYtU0hBMzg0OkVDREhFLVJTQS1BRVMyNTYtU0hBOkVDREhFLUVDRFNBLUFFUzI1Ni1TSEE6REhFLVJTQS1BRVMxMjgtU0hBMjU2OkRIRS1SU0EtQUVTMTI4LVNIQTpESEUtRFNTLUFFUzEyOC1TSEEyNTY6REhFLVJTQS1BRVMyNTYtU0hBMjU2OkRIRS1EU1MtQUVTMjU2LVNIQTpESEUtUlNBLUFFUzI1Ni1TSEE6IWFOVUxMOiFlTlVMTDohRVhQT1JUOiFERVM6IVJDNDohM0RFUzohTUQ1OiFQU0snOwoKCQlzc2xfc3RhcGxpbmcgb247CgkJc3NsX3N0YXBsaW5nX3ZlcmlmeSBvbjsKCgkJc2VydmVyX25hbWUgZmlyZWJhc2UuY3lwaC5jb207CgoJCWxvY2F0aW9uIC92MC9iL2N5cGhtZS5hcHBzcG90LmNvbSB7CgkJCWFkZF9oZWFkZXIgJ0FjY2Vzcy1Db250cm9sLUFsbG93LU9yaWdpbicgJyonOwoJCQlwcm94eV9wYXNzIGh0dHBzOi8vZmlyZWJhc2VzdG9yYWdlLmdvb2dsZWFwaXMuY29tOwoJCX0KCX0KfQo='


cd $(cd "$(dirname "$0")"; pwd)
dir="$(pwd)"

sed -i 's/# deb /deb /g' /etc/apt/sources.list
sed -i 's/\/\/.*archive.ubuntu.com/\/\/archive.ubuntu.com/g' /etc/apt/sources.list

export DEBIAN_FRONTEND=noninteractive
apt-add-repository -y ppa:nginx/development
apt-get -y --force-yes update
apt-get -y --force-yes upgrade
apt-get -y --force-yes install aptitude nginx openssl unzip

mkdir /opt/certbot
cd /opt/certbot
wget https://github.com/certbot/certbot/archive/master.zip
unzip master.zip
rm master.zip
certbotdir="$(ls)"
mv $certbotdir/* ./
rm -rf $certbotdir

/opt/certbot/certbot-auto certonly \
	-n \
	--agree-tos \
	--standalone \
	--force-renewal \
	-d firebase.cyph.com \
	--email firebaseproxy@cyph.com

mkdir /etc/nginx/ssl
chmod 600 /etc/nginx/ssl
openssl dhparam -out /etc/nginx/ssl/dhparams.pem 2048
ln -s /etc/letsencrypt/live/firebase.cyph.com/privkey.pem /etc/nginx/ssl/key.pem
ln -s /etc/letsencrypt/live/firebase.cyph.com/cert.pem /etc/nginx/ssl/cert.pem

echo "${conf}" | base64 --decode | sed "s/worker_connections 768;/worker_connections $(ulimit -n);/g" > /etc/nginx/nginx.conf

rm $dir/firebaseproxysetup.sh
reboot
